### ISSUE TITLE
Several panics with red_knot

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#13448]
Red knot 7441da287fd8438c69d444a4df551f032167ebb2
command:
```
red_knot
```
panics

- [ ] -
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/types/infer.rs:2480:17:
name in a type expression is always 'load' but got: 'Invalid'
```
- [ ] -
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/semantic_index/builder.rs:215:9:
assertion `left == right` failed
  left: Some(Definition { [salsa id]: Id(12886), file: File { [salsa id]: Id(c5c), path: System("/home/rafal/test/C/assertion_left_right_9557295343497515986.py"), permissions: Some(33204), revision: FileRevision(31858149924950276665155673931), status: Exists, count: Count { ghost: PhantomData<fn(ruff_db::files::File)> } }, file_scope: FileScopeId(21), symbol: ScopedSymbolId(5), kind: AnnotatedAssignment(AstNodeRef(StmtAnnAssign { range: 12880..12914, target: Tuple(ExprTuple { range: 12880..12913, elts: [Name(ExprName { range: 12881..12895, id: Name("TransportError"), ctx: Store }), Name(ExprName { range: 12897..12912, id: Name("ConnectionError"), ctx: Store })], ctx: Store, parenthesized: true }), annotation: Name(ExprName { range: 12914..12914, id: Name(""), ctx: Invalid }), value: None, simple: false })), count: Count { ghost: PhantomData<fn(red_knot_python_semantic::semantic_index::definition::Definition)> } })
 right: None

```
- [ ] -
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/types/infer.rs:1608:9:
assertion `left == right` failed
  left: Some(Unknown)
 right: None

```
- [ ] -
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/types/infer.rs:192:25:
no entry found for key
```
- [ ] -
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/types/infer.rs:2613:9:
assertion failed: previous.is_none()
```

Files - [C.zip](https://github.com/user-attachments/files/17091206/C.zip)

This is a cumulative issue, because I don't want to pollute the issue tracker with errors, especially when red_knot is not yet fully released.

The files are not minimized because a single run of red_knot on a folder with one small file takes ~1 second, making minimization time consuming(in opposite to ruff)

**Comment by sharkdp** [comment]
Thank you very much for providing this corpus. It helped a lot in finding some bugs. With #14091, #14306, #14312, #14317, #14325, (#14326) and #14337 merged, we can now run red knot on all files in your corpus without panicking.
