### ISSUE TITLE
hello , god blessing you , when I run node ruff.js  ,    here  are  error   ,what do I do   

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/ruff#13661]
win11  ruff 0.6.9 

![image](https://github.com/user-attachments/assets/6a72b9cf-894d-417c-b92f-431095102a04)

#  running  error
```
using deprecated parameters for the initialization function; pass a single object instead
Error: TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at async __wbg_init (file:///A:/GitHub_Learning_Completed_Course/100+%20Python%20%E9%A1%B9%E7%9B%AE%E6%8C%91%E6%88%98/ruff-playgroud/black-playground/web/node_modules/.pnpm/@astral-sh+ruff-wasm-web@0.6.9/node_modules/@astral-sh/ruff-wasm-web/ruff_wasm.js:815:51)
    at async runRuff (file:///a:/GitHub_Learning_Completed_Course/100+%20Python%20%E9%A1%B9%E7%9B%AE%E6%8C%91%E6%88%98/ruff-playgroud/black-playground/web/src/lib/ruff.js:12:3) {
  [cause]: Error: not implemented... yet...
      at makeNetworkError (node:internal/deps/undici/undici:8968:35)
      at schemeFetch (node:internal/deps/undici/undici:10363:34)
      at node:internal/deps/undici/undici:10212:26
      at mainFetch (node:internal/deps/undici/undici:10231:11)
      at fetching (node:internal/deps/undici/undici:10179:7)
      at fetch (node:internal/deps/undici/undici:10048:20)
      at fetch (node:internal/deps/undici/undici:13183:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at __wbg_init (file:///A:/GitHub_Learning_Completed_Course/100+%20Python%20%E9%A1%B9%E7%9B%AE%E6%8C%91%E6%88%98/ruff-playgroud/black-playground/web/node_modules/.pnpm/@astral-sh+ruff-wasm-web@0.6.9/node_modules/@astral-sh/ruff-wasm-web/ruff_wasm.js:810:26)
      at runRuff (file:///a:/GitHub_Learning_Completed_Course/100+%20Python%20%E9%A1%B9%E7%9B%AE%E6%8C%91%E6%88%98/ruff-playgroud/black-playground/web/src/lib/ruff.js:12:9)
} 
```

**Comment by MichaReiser** [comment]
Are you running the code in node? If so, then you want to use the `ruff-wasm-nodejs` package https://www.npmjs.com/package/@astral-sh/ruff-wasm-nodejs

**Comment by Super1Windcloud** [comment]
![image](https://github.com/user-attachments/assets/45b768a1-a232-4c11-bc57-d5ff6e5e0511)


example is fault  , I  have to  read source to  use  api

**Comment by MichaReiser** [comment]
I'm not sure I understand. Were you able to resolve the issue?
