### ISSUE TITLE
[red-knot] Panics on generic type alias

### ISSUE THREAD

**Issue by sharkdp** [astral-sh/ruff#14307]
Red knot currently panics when encountering [PEP-695 generic type aliases](https://peps.python.org/pep-0695/#generic-type-aliases):
```py
type ListOrSet[T] = list[T] | set[T]
```

Backtrace:
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/types/infer.rs:872:37:
no entry found for key
stack backtrace:
[…]
   6: red_knot_python_semantic::semantic_index::SemanticIndex::definition
             at ./crates/red_knot_python_semantic/src/semantic_index.rs:210:33
   7: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_definition
             at ./crates/red_knot_python_semantic/src/types/infer.rs:872:26
   8: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_type_parameters
             at ./crates/red_knot_python_semantic/src/types/infer.rs:4036:50
   9: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_type_alias_statement
             at ./crates/red_knot_python_semantic/src/types/infer.rs:1805:13
  10: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_statement
             at ./crates/red_knot_python_semantic/src/types/infer.rs:851:53
  11: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_body
             at ./crates/red_knot_python_semantic/src/types/infer.rs:831:13
  12: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_module
             at ./crates/red_knot_python_semantic/src/types/infer.rs:793:9
  13: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_region_scope
             at ./crates/red_knot_python_semantic/src/types/infer.rs:417:17
  14: red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_region
             at ./crates/red_knot_python_semantic/src/types/infer.rs:405:46
  15: red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish
             at ./crates/red_knot_python_semantic/src/types/infer.rs:4044:9
```

**Comment by sharkdp** [comment]
Fixing this probably involves understanding `type … = …` statements as having their own annotation scope (https://docs.python.org/3/reference/simple_stmts.html#the-type-statement).
