### ISSUE TITLE
no UP031 fix for `"%d" % 1`

### ISSUE THREAD

**Issue by njzjz** [astral-sh/ruff#14600]
Ruff 0.8.0
Minimal example:
```py
"%d" % 1
```
https://play.ruff.rs/2acb42ef-d5d7-4dc0-a649-2b7ff4e174f2

```
ruff check up031.py --select UP031 --fix --unsafe-fixes
up031.py:1:1: UP031 Use format specifiers instead of percent format
  |
1 | "%d" % 1
  | ^^^^ UP031
  |
  = help: Replace with format specifiers

Found 1 error.
```

There is no fix, even no unsafe fix. But there is a fix if `%d` is replaced by `%f`. Isn't the logic similar here?

In a real project, there are hundreds of errors like this.

**Comment by MichaReiser** [comment]
> There is no fix, even no unsafe fix. But there is a fix if %d is replaced by %f. Isn't the logic similar here?

The logic is similar but what's different to `%s` is that all parameters need to be wrapped in `int(parameter)` to avoid changing behavior. 

```py
>>> "a %d" % 2.34
'a 2'
>>> f"a {2.34}"
'a 2.34'

>>> "a %d" % "test"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %d format: a real number is required, not str
>>> f"a {'test'}"
'a test'
```

We would get the same behavior when wrapping the parameter with `int`

```py
>>> f"a {int(2.34)}"
'a 2'
>>> f"a {int('test')}"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'test'
```

Unfortunately, Ruff doesn't understand today whether the parameter is an int literal or not, which is why the fix would have to wrap all parameters with `int`, which may or may not be what users want.

**Comment by Skylion007** [comment]
Wouldn't just "a {int(2.34):d}" be equivalent?
