### ISSUE TITLE
Rule ANN204 cause panic (looks like fstring regression)

### ISSUE THREAD

**Issue by qarmin** [astral-sh/ruff#7711]
Ruff 0.0.291 (latest changes from main branch)
```
ruff  *.py --select ANN204 --no-cache --fix --preview
```

file content:
```
class Epi(Base):
    def __init__(
    ):
        log.debug(f"{self.epi_eE_pr=}")
```

error
```

error: Panicked while linting /home/rafal/test/tmp_folder/F_NAME_1765994490202376285746.py: This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BLinter%20panic%5D

...with the relevant file contents, the `pyproject.toml` settings, and the following stack trace, we'd be very appreciative!

panicked at 'byte index 85 is out of bounds of `class Epi(Base):
    def __init__(
    ):
        log.debug(f"{self.epi_eE_pr=}")`', crates/ruff_python_parser/src/python.rs:36231:27
Backtrace:    0: ruff_cli::panic::catch_unwind::{{closure}}
             at /home/rafal/test/ruff/crates/ruff_cli/src/panic.rs:31:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:709:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
   5: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   6: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   7: core::str::slice_error_fail_rt
   8: core::str::slice_error_fail
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/str/mod.rs:87:9
   9: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/str/traits.rs:235:21
  10: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/str/traits.rs:61:15
  11: ruff_text_size::range::<impl core::ops::index::Index<ruff_text_size::range::TextRange> for str>::index
             at /home/rafal/test/ruff/crates/ruff_text_size/src/range.rs:430:10
  12: ruff_python_parser::python::__action218::{{closure}}
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:36231:27
  13: core::option::Option<T>::map
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/option.rs:1075:29
  14: ruff_python_parser::python::__action218
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:36219:32
  15: ruff_python_parser::python::__action674
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:44268:5
  16: ruff_python_parser::python::__action804
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:48392:5
  17: ruff_python_parser::python::__action1314
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:64341:5
  18: ruff_python_parser::python::__action1569
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:72158:5
  19: ruff_python_parser::python::__action1575
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:72355:5
  20: ruff_python_parser::python::__parse__Top::__reduce
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:13865:34
  21: <ruff_python_parser::python::__parse__Top::__StateMachine as lalrpop_util::state_machine::ParserDefinition>::reduce
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:5943:13
  22: lalrpop_util::state_machine::Parser<D,I>::reduce
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lalrpop-util-0.20.0/src/state_machine.rs:594:9
  23: lalrpop_util::state_machine::Parser<D,I>::parse
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lalrpop-util-0.20.0/src/state_machine.rs:264:43
  24: lalrpop_util::state_machine::Parser<D,I>::drive
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lalrpop-util-0.20.0/src/state_machine.rs:218:9
  25: ruff_python_parser::python::__parse__Top::TopParser::parse
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/python.rs:11833:13
  26: ruff_python_parser::parser::parse_filtered_tokens
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/parser.rs:258:5
  27: ruff_python_parser::parser::parse_tokens
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/parser.rs:223:5
  28: ruff_python_parser::parse_program_tokens
             at /home/rafal/test/ruff/crates/ruff_python_parser/src/lib.rs:158:11
  29: ruff_linter::linter::check_path
             at /home/rafal/test/ruff/crates/ruff_linter/src/linter.rs:144:15
  30: ruff_linter::linter::lint_fix
             at /home/rafal/test/ruff/crates/ruff_linter/src/linter.rs:461:22
  31: ruff_cli::diagnostics::lint_path
             at /home/rafal/test/ruff/crates/ruff_cli/src/diagnostics.rs:228:14
  32: ruff_cli::commands::check::lint_path::{{closure}}
             at /home/rafal/test/ruff/crates/ruff_cli/src/commands/check.rs:204:9
  33: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  34: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  35: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  36: ruff_cli::panic::catch_unwind
             at /home/rafal/test/ruff/crates/ruff_cli/src/panic.rs:40:18
  37: ruff_cli::commands::check::lint_path
             at /home/rafal/test/ruff/crates/ruff_cli/src/commands/check.rs:203:18
  38: ruff_cli::commands::check::check::{{closure}}
             at /home/rafal/test/ruff/crates/ruff_cli/src/commands/check.rs:122:21
  39: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:272:13
  40: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/iter/adapters/map.rs:84:28
  41: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/slice/iter/macros.rs:215:27
  42: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/iter/adapters/map.rs:124:9
  43: <rayon::iter::reduce::ReduceFolder<R,T> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/reduce.rs:105:19
  44: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:248:21
  45: rayon::iter::plumbing::Producer::fold_with
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:110:9
  46: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:438:13
  47: rayon::iter::plumbing::bridge_producer_consumer
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:397:12
  48: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:373:13
  49: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/slice/mod.rs:732:9
  50: rayon::iter::plumbing::bridge
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/plumbing/mod.rs:357:12
  51: <rayon::slice::Iter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/slice/mod.rs:708:9
  52: <rayon::iter::map::Map<I,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/map.rs:49:9
  53: rayon::iter::reduce::reduce
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/reduce.rs:15:5
  54: rayon::iter::ParallelIterator::reduce
             at /home/rafal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.8.0/src/iter/mod.rs:991:9
  55: ruff_cli::commands::check::check
             at /home/rafal/test/ruff/crates/ruff_cli/src/commands/check.rs:173:10
  56: ruff_cli::check
             at /home/rafal/test/ruff/crates/ruff_cli/src/lib.rs:372:13
  57: ruff_cli::run
             at /home/rafal/test/ruff/crates/ruff_cli/src/lib.rs:163:33
  58: ruff::main
             at /home/rafal/test/ruff/crates/ruff_cli/src/bin/ruff.rs:49:11
  59: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  60: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:135:18
  61: main
  62: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  63: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  64: _start


```

**Comment by charliermarsh** [comment]
Thank you!
