### ISSUE TITLE
Avoid undefined-name errors for recursive calls after deletions

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#7733]
Given:

```python
def func(x: int):
    if x > 0:
        func(x - 1)
    print(x)

func(1)
del func
```

Ruff reports an undefined name (F821) on the inner `func` call, because it's deleted in the outer scope. This is hard to solve in general, but given that the function must exist in order for it to be called, we should be able to do better here.

See: https://github.com/python-trio/trio/pull/2795#discussion_r1341908880.

**Comment by A5rocks** [comment]
I suppose that a quick sanity check for whatever solution (if there is one) is that this should still fail...
```py
>>> def f(x):
...   if x: f(False)
...
>>> z = f
>>> z(True)
>>> del f
>>> z(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
NameError: name 'f' is not defined
```

... but I think as long as you just assume the worst if reassignment happens, then this shouldn't have other issues.

**Comment by joaoleveiga** [comment]
Any recommendations here? I am not sure if I should open a new issue or not but should this feature capture situations such as:

```python
# script.py
X = "default value"

def main():
    def f():
        print(X)

    if False:
        X = "new value"
    f()

main()
```

```
$ python script.py
NameError: free variable 'X' referenced before assignment in enclosing scope
```
