### ISSUE TITLE
new rule - not calling super() in custom exception's __init__()

### ISSUE THREAD

**Issue by m-aciek** [astral-sh/ruff#8579]
```python
class CustomException(Exception):
    def __init__(self, custom: int, arguments: str) -> None:
        self.msg = f"Something specific happened with custom: {int} and {arguments}"
```

In my personal experience above exception class is quite a common mistake. The implementer assumes, that they will use the `self.msg` parameter during exception handling. The issue araises when the exception gets anywhere else as the its string representation is as follows:

```python
>>> raise CustomException(42, 'test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException: (42, 'test')
```

and when the exception is instantiated with keyword arguments, we loose the information about the arguments' values.

```python
>>> raise CustomException(custom=1, arguments='two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException
```

How to fix it? By calling `super().__init__()` in the constructor.
```python
class CustomException(Exception):
    def __init__(self, custom: int, arguments: str) -> None:
        self.msg = "Something specific happened with custom: {int} and {arguments}"
        super().__init__(self.msg)
>>> raise CustomException(1, 'two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException: Something specific happened with custom: 1 and two
>>> raise CustomException(custom=1, parameters='two')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
__main__.CustomException: Something specific happened with custom: 1 and two
```

**Specification proposal**

If a class:
* inherits from from `Exception`,
* doesn't implement own `__str__()` method,
* its `__init__()` method doesn't enforce any positional-only argument, 
* and doesn't call `super().__init__()` in its `__init__()` method
Then:
* new rule should raise an error, calling to fix it.

**Comment by opk12** [comment]
Related: linting for a missing `super` call in *any* `__init__()` (not only inside exception classes) is tracked in #970 (`implement Pylint`) as the list item `super-init-not-called / W0231`.

**Comment by jakkdl** [comment]
https://github.com/PyCQA/flake8-bugbear/pull/512 has now been merged upstream
