### ISSUE TITLE
`pip install .` from src is failing

### ISSUE THREAD

**Issue by Skylion007** [astral-sh/ruff#9975]
* I git cloned the latest main.
* Ran `pip install -vv .` in the root directory
* Hit the following error:
```
Using pip 24.0 from /Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-build-tracker-tl9e__1m
Initialized build tracking at /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-build-tracker-tl9e__1m
Created build tracker: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-build-tracker-tl9e__1m
Entered build tracker: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-build-tracker-tl9e__1m
Created temporary directory: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-install-rl8b7g2j
Created temporary directory: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-ephem-wheel-cache-9jnzxe4w
Processing /Users/agokaslan/git/ruff
  Added file:///Users/agokaslan/git/ruff to build tracker '/private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-build-tracker-tl9e__1m'
  Created temporary directory: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-build-env-y4y6m2mj
  Running command pip subprocess to install build dependencies
  Using pip 24.0 from /Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip (python 3.8)
  Collecting maturin<2.0,>=1.0
    Obtaining dependency information for maturin<2.0,>=1.0 from https://files.pythonhosted.org/packages/6b/fb/95fd7476bdf9565a45e14e3211e94dd87109d3a2d9dcfaaeef5e211a5cfc/maturin-1.4.0-py3-none-macosx_10_12_x86_64.whl.metadata
    Using cached maturin-1.4.0-py3-none-macosx_10_12_x86_64.whl.metadata (18 kB)
  Collecting tomli>=1.1.0 (from maturin<2.0,>=1.0)
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Using cached maturin-1.4.0-py3-none-macosx_10_12_x86_64.whl (8.0 MB)
  Installing collected packages: tomli, maturin
  Successfully installed maturin-1.4.0 tomli-2.0.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Created temporary directory: /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-modern-metadata-wfcqvutd
  Running command Preparing metadata (pyproject.toml)
  error: failed to load manifest for workspace member `/Users/agokaslan/git/ruff/crates/ruff_cli`

  Caused by:
    failed to read `/Users/agokaslan/git/ruff/crates/ruff_cli/Cargo.toml`

  Caused by:
    No such file or directory (os error 2)
  💥 maturin failed
    Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
    Caused by: `cargo metadata` exited with an error:
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-modern-metadata-wfcqvutd', '--interpreter', '/Users/agokaslan/venvs/ai_habitat_sys_py3/bin/python']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/pip-modern-metadata-wfcqvutd --interpreter /Users/agokaslan/venvs/ai_habitat_sys_py3/bin/python`
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/agokaslan/venvs/ai_habitat_sys_py3/bin/python /Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/mv/ql5dp3xj2wd5f1n45w8jv6z00000gn/T/tmpoydyvpvc
  cwd: /Users/agokaslan/git/ruff
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Exception information:
Traceback (most recent call last):
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 766, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
    reqs = list(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 579, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/Users/agokaslan/venvs/ai_habitat_sys_py3/lib/python3.8/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
```
Running `python 3.8.2` pip build 24.0 . Does ruff actually not support building itself on python 3.8?

**Comment by charliermarsh** [comment]
Do you know where the `ruff_cli` reference is coming from? That crate was renamed to `ruff`. (Do you happen to have a `crates/ruff_cli` folder lingering in your local directory?)

**Comment by Skylion007** [comment]
`rm -rf  crates/ruff_cli` fixed it. There was a `resources` folder in there.
